// src/lidar/utils/pcd.util.ts
import * as fs from 'fs';

export type Point = [number, number, number, number]; // x y z intensity

export function writePCDAscii(path: string, points: Point[]) {
  const n = points.length;
  const header = `# generated by NestJS
VERSION .7
FIELDS x y z intensity
SIZE 4 4 4 4
TYPE F F F F
COUNT 1 1 1 1
WIDTH ${n}
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS ${n}
DATA ascii
`;

  const body =
    points.map((p) => `${p[0]} ${p[1]} ${p[2]} ${p[3]}`).join('\n') + '\n';
  fs.writeFileSync(path, header + body, 'utf8');
}
